import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging.ems.devdolphins.com/welcome');
  await page.getByLabel('Employee ID:').click();
  await page.getByLabel('Employee ID:').fill('');
  await page.getByLabel('Employee ID:').click();
  await page.getByLabel('Password:').click();
  await page.getByLabel('Password:').fill('123456');
  await page.getByLabel('Password:').press('Enter');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'My Profile' }).click();
  await page.goto('https://staging.ems.devdolphins.com/user/home');
  await page.getByRole('link', { name: 'Update Password' }).click();
  await page.getByLabel('New Password:').click();
  await page.getByLabel('New Password:').fill('123456');
  await page.getByLabel('Confirm Password:').click();
  await page.getByLabel('Confirm Password:').fill('123456');
  await page.getByRole('button', { name: 'Update Password' }).click();
  await page.getByRole('link', { name: 'Back to Home Page' }).click();
  await page.getByRole('link', { name: 'Leave Management' }).click();
  await page.getByRole('link', { name: 'Request Leave' }).click();
  await page.getByLabel('Type of Leave:').selectOption('casual');
  await page.getByLabel('Date of Leave:').fill('2025-01-04');
  await page.getByLabel('End Date:').fill('2025-01-04');
  await page.getByLabel('Reason:').click();
  await page.getByLabel('Reason:').fill('beacause it is sunday');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://staging.ems.devdolphins.com/leaveRequest');
  await page.getByRole('link', { name: 'DevDolphins DevDolphins' }).click();
  await page.getByRole('link', { name: 'Leave Management' }).click();
  await page.getByRole('link', { name: 'Leave Balance' }).click();
  await page.getByText('Total Leaves:').click();
  await page.getByText('Leave Balance Total Leaves:').click();
  await page.getByRole('link', { name: 'My Profile' }).click();
  await page.getByRole('link', { name: 'DevDolphins DevDolphins' }).click();
  await page.getByRole('link', { name: '' }).click();
  await page.getByRole('link', { name: 'My Corner' }).click();
  await page.getByRole('link', { name: 'View Attendance' }).click();
  await page.getByRole('link', { name: 'My Leaves' }).click();
  await page.getByRole('link', { name: ' Delete' }).click();
});